apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: idpadmins
  description: The infra business unit
spec:
  type: teamA
  profile:
    displayName: Infrastructure
    email: infrastructure@example.com
    picture: https://example.com/groups/bu-infrastructure.jpeg
  parent: ops
  children: [backstage, other]
  members: [jdoe]
